# Generated by Django 4.0.4 on 2022-08-15 08:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Netflixapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webseries',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='webseries',
            name='type',
            field=models.CharField(choices=[('episode', 'Episode')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webseries',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
